spring.application.name=new-project

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
